### PR TITLE
Use parsoid-external-ci-access.beta.wmflabs.org for testing

### PR DESCRIPTION
**Pull request by cscott**
Bug: T247589

### CODE REVIEW

**Comment by cscott** [comment]
Two failing tests:
'item requests > should request page lints. no revision:' is failing for some reason, even though this works fine from CLI:
```
curl -d '{}' -X POST -H 'Content-Type: application/json' -H 'Host: en.wikipedia.beta.wmflabs.org' http://parsoid-external-ci-access.beta.wmflabs.org/w/rest.php/en.wikipedia.beta.wmflabs.org/v3/transform/wikitext/to/lint/User%3APchelolo%2FLintTest

curl -d '{}' -X POST -H 'Content-Type: application/json' -H 'Host: en.wikipedia.beta.wmflabs.org' http://parsoid-external-ci-access.beta.wmflabs.org/w/rest.php/en.wikipedia.beta.wmflabs.org/v3/transform/wikitext/to/lint/User%3APchelolo%2FLintTest/409437
```
It seems to be the redirect which is causing problems, since the redirect goes to:
https://en.wikipedia.beta.wmflabs.org/w/rest.php/en.wikipedia.beta.wmflabs.org/v3/transform/wikitext/to/lint/User%3APchelolo%2FLintTest/409437
not `parsoid-external-ci-access.beta.wmflabs.org`

Second failure is 'router - security > should forward cookies on request to parsoid'.
That gets an assertion error "Mocks not satisfied".  Probably the mock needs to be updated?

**Comment by cscott** [comment]
Ok, this should fix the tests.

It's *possible* the issue with `parsoid.js:getLintErrors()` is a parsoid bug with how the redirect is generated.

There are some transient failures which seem to be caused by github parallelizing the tests which create and mutate https://en.wikipedia.beta.wmflabs.org/wiki/Save_test

**Comment by cscott** [comment]
The "prevent concurrent execution" thing doesn't actually seem to work.  The page name should include `node-version`, `cassandra-version`, `test-target`, and `test-mode` to prevent conflicts, instead of trying to keep the test runs separate.

**Comment by cscott** [comment]
OK, this is good now.

**Comment by Pchelolo** [comment]
Hm.. thank you for setting up the parsoid-ci-access, however with the test fixes - I'm not sure they're correct. For example the page_save test that you're setting the page via an env variable now is actually completely mocked and should be not calling real services (we were getting complaints for creating gazillion pages on beta).

I think I should just take it on from here and try to poke some other approaches to fixing those tests, there's probably just something hardcoded somewhere, `nock` is not a very user-friendly library to debug..

**Comment by Pchelolo** [comment]
Superseded by #1248 - mostly same code, thank you @cscott, just changed the save_api to actually use the mocks - we have switched that off cause parsoid and MW was sharing the domain and we couldn't use nock properly, now they don't so we can return to using the mocks.

**Pull request closed without merging**
