### PR TITLE
Remove the IPA from an extract

### PR DESCRIPTION
**Pull request by Pchelolo**
I've looked through several articles and came up with these regexes, but suggestions on improvement are very welcome.

cc @wikimedia/services 

Bug: https://phabricator.wikimedia.org/T135272

### CODE REVIEW

**Comment by gwicke** [comment]
Doing this regexp-based looks dangerous, especially considering the lack of syntactical guarantees we have on PHP parser output. This is all past-sanitizer, so a mistake in regexp massaging could create XSS issues. It would be more reliable to use template information from Parsoid to reliably identify & strip IPA content on a DOM, ideally in the content service.

I think the plan was to move the summary backend to MCS longer term anyway, so perhaps this would be a good reason to look into that move sooner?

**Comment by Pchelolo** [comment]
@gwicke I completely agree that's dangerous, I've started this PR mostly to begin the conversation about this issue.

**Comment by berndsi** [comment]
> I think the plan was to move the summary backend to MCS longer term anyway

I was not aware of that but that's an interesting thought.

**Comment by Pchelolo** [comment]
Since we've decided not to do it this way, I'm closing this PR

**Pull request closed without merging**
