### PR TITLE
Remove the old summary implementation

### PR DESCRIPTION
**Pull request by Pchelolo**
After we complete the migration to the new MCS-based summary we'd need to clean up the code and remove the old implementation.

cc @wikimedia/services @berndsi

### CODE REVIEW

**Comment by d00rman** [comment]
Hm, this makes a hard dependency on MCS for summary. Maybe we could keep the old version around for other users who might be happy with the TextExtracts variant?

**Comment by Pchelolo** [comment]
> Hm, this makes a hard dependency on MCS for summary. Maybe we could keep the old version around for other users who might be happy with the TextExtracts variant?

Do you think such users even exist?

**Comment by d00rman** [comment]
@Pchelolo AFAIK, if people install RESTBase, it's most likely for VE. If we keep this code in, then they get page previews via RB for free which is a nice usage scale up

**Comment by Pchelolo** [comment]
Ok, makes sence.

**Pull request closed without merging**
