### PR TITLE
Metrics naming consistency: Rename 'private' to 'internal'

### PR DESCRIPTION
**Pull request by gwicke**
Should only be merged / deployed in coordination with a rename of the graphite
metrics.

### CODE REVIEW

**Comment by Pchelolo** [comment]
@gwicke I'm wondering if it would be more consistent if external requests have an `external` prefix? Right now it's not really obvious that non-prefixed metrics are external.

**Comment by gwicke** [comment]
@Pchelolo, we could consider changing that too, but the trade-offs involved in that change are different. We'd have to update a lot of dashboards to use the new 'external' prefix. On the plus side, summing all requests (internal, internal_update, external) would be simpler that way.

**Comment by d00rman** [comment]
> I'm wondering if it would be more consistent if external requests have an external prefix? Right now it's not really obvious that non-prefixed metrics are external.

+1

> we could consider changing that too, but the trade-offs involved in that change are different. We'd have to update a lot of dashboards to use the new 'external' prefix.

That's true, but yesterday @eevans started updating some of the dashboards, and it seems to me now that we might want to add some new dashboards / rows for different prefixes (e.g. parsoid performance is mostly relevant to internal-update requests, while storage 2xx latencies are important for external users mostly). I have a feeling we'll need to change quite a lot of stuff regardless of the `external` prefix.

> On the plus side, summing all requests (internal, internal_update, external) would be simpler that way.

Yup, that's a bit messy / clumsy in the current state.

**Comment by gwicke** [comment]
Okay, so we'll need to deploy this in coordination with an ops, mostly likely Filippo, so that we can rename the metrics in sync with the deploy to minimize metric loss.

I'm +1 for adding the external/ prefix as well, we'll just need to spend some time doing those dashboard fix-ups.

**Comment by d00rman** [comment]
cc @filippog for context and background :)

**Comment by filippog** [comment]
:+1:

I'll rename `private` to `internal` just before restbase restarts, that should minimize the loss

**Comment by d00rman** [comment]
Great, cheers @filippog ! @gwicke how about getting that `external` prefix in as well?

**Comment by gwicke** [comment]
Seperseded by https://github.com/wikimedia/hyperswitch/pull/6, which also includes the `external` prefix change.

**Pull request closed without merging**
