### PR TITLE
Remove pngs from math endpoint

### PR DESCRIPTION
**Pull request by physikerwelt**
Bug: T311620
Change-Id: I7dc8be1900d2d7b502f7e66e7f3207404a8b3dec

### CODE REVIEW

**Comment by physikerwelt** [comment]
cf. https://gerrit.wikimedia.org/r/c/mediawiki/services/restbase/+/869763

**Comment by johngian** [comment]
Codewise it looks OK. Meanwhile i am trying to fix the tests so CI can pass.

**Comment by physikerwelt** [comment]
@johngian cool. Can you also deploy to beta?

**Comment by johngian** [comment]
Please rebase to latest changes.

**Comment by physikerwelt** [comment]
@johngian thank you for fixing the test. Now the tests pass.

**Comment by brightbyte** [comment]
Do I understand correctly that this will remove support for the https://wikimedia.org/api/rest_v1/media/math/render/png endpoint? I am seeing 64k requests per hour there... So something is apparently using it? https://w.wiki/6PEA

**Comment by physikerwelt** [comment]
I can't see the stats. Maybe the requests come from non-WMF wikis. The change was announced in technews (https://en.wikipedia.org/wiki/Wikipedia:Village_pump_(technical)/Archive_201#Tech_News:_2022-48) and discussed here https://phabricator.wikimedia.org/T311620#8400577. People running math extensions before https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Math/+/858661 (approx 1.40.0-wmf.12) still would trigger requests from people using their websites.

**Comment by brightbyte** [comment]
Looks like you are right - according to the Referrer header, nearly all of them come from Fandom.

**Comment by mszabo-wikia** [comment]
Hi all,

We've expedited the work to disable PNG rendering support and hope to do it as soon as we determine whether there's a need for any user communication.

We've also reprioritized the work to (in the medium/long term) move off the WMF infrastructure for Math rendering.

Thank you for your patience and understanding.

**Comment by physikerwelt** [comment]
Math development is mostly driven by the community. You can join us here https://meta.wikimedia.org/wiki/Wikimedia_Community_User_Group_Math

**Comment by mszabo-wikia** [comment]
We just deployed a change to disable PNG rendering for math & chem formulas, so hopefully this change should be unblocked momentarily.

**Comment by physikerwelt** [comment]
@mszabo-wikia thank you. @brightbyte can you double check please?

**Comment by brightbyte** [comment]
Requests are down by 85%. Still seeing about two requests per second, though (down from 15). Let's see how it looks tomorrow.

**Comment by physikerwelt** [comment]
@brightbyte do you think it would make sense to backport the change to 1_39 REL (I guess not everyone might be willing to upgrade to 1_40 REL)

**Comment by brightbyte** [comment]
> @brightbyte do you think it would make sense to backport the change to 1_39 REL (I guess not everyone might be willing to upgrade to 1_40 REL)

Are we even doing releases of RESTbase? I'm not seeing release branches or anything like that.

**Comment by physikerwelt** [comment]
@brightbyte The requests are initiated by the Math extension. And these extensions follow the regular release cycle. My suggestion would be https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Math/+/898882

**Comment by brightbyte** [comment]
Looks like the hits originating from Fandom are pretty much gone now. 
We are seeing about one req/sec coming from paradoxplaza.com wikis, see https://wikis.paradoxplaza.com/.

**Comment by physikerwelt** [comment]
I can redo the removal of PNG rendering mode on 1.35 (there are too many other code changes between 1.35 and 1.39). 
Also note that there are two reasons of why PNG images are being requested. For one the browser feels that it can not serve SVG images and asks for PNG.



However, if we run node <=10 in restbase anyhow, I don't see any reason to hurry. It depends on the urgency to remove node 10. I was under the impression that this would be very urgent.

**Comment by brightbyte** [comment]
Can you make a wiki page explaining the removal of PNG support, with instructions of how to fix it on 3rd party wikis?

We could then make requests for PNG redirect to a single PNG file that points to that wiki page.

**Comment by brightbyte** [comment]
> However, if we run node <=10 in restbase anyhow, I don't see any reason to hurry. It depends on the urgency to remove node 10. I was under the impression that this would be very urgent.

That I don't know.

**Comment by johngian** [comment]
How is the node version of restbase related to the mathoid service?

**Comment by physikerwelt** [comment]
> Can you make a wiki page explaining the removal of PNG support, with instructions of how to fix it on 3rd party wikis?

Yes



> How is the node version of restbase related to the mathoid service?

We must remove png support from mathoid as the node librsvg binding does not work on node versions > 10. If we keep services running on node 10 anyhow, I think it does not matter if there is one or two services running with node 10.

**Comment by johngian** [comment]
I think there are a few things that are not necessarily coupled:

* Does the fact that MW 1.35 has support until end of 2023 mean that also extensions have the same support? From the math extension it looks like the requirement is `>=1.40`.
*  Since the node upgrade is inevitable sooner or later I think it makes sense to communicate with the consumers left using png for the upcoming deprecation.
* The main issue that I see is [that the endpoint ](https://en.wikipedia.org/api/rest_v1/#/Math/get_media_math_render__format___hash_) is considered stable so a signature change shouldn't happen without further communications and deprecation. 

@physikerwelt Other than the technical aspect (disabling png on RESTBase and updating the backing service) to me it makes sense to:
* Announce to a mailing list with a broader audience about the upcoming deprecation (mostly for external consumers).
* Update the swagger docs on the endpoint
* When we end up with an amount of reqs that we feel comfortable disable png on restbase.

I think since this discussion has little to do with actual restbase, lets move it to phabricator for better visibility.

**Comment by brightbyte** [comment]
> Does the fact that MW 1.35 has support until end of 2023 mean that also extensions have the same support? From the math extension it looks like the requirement is >=1.40.

My thinking is that the version of Math that was released along with MW 1.35 should not break as long as 1.35 is supported. The fact that the current version of Math requires MW 1.40 isn't relevant for that. Websites that run MW 1.35 with Math are relying on the service, and should be able to as long as 1.35 is supported.

**Comment by jdforrester** [comment]
> > Does the fact that MW 1.35 has support until end of 2023 mean that also extensions have the same support? From the math extension it looks like the requirement is >=1.40.
> 
> My thinking is that the version of Math that was released along with MW 1.35 should not break as long as 1.35 is supported. 

Math wasn't a supported release until 1.38 when we started bundling it in the tarball. I don't think you should do any extra work to try to support 1.35 in staff time.

**Comment by physikerwelt** [comment]
I am happy to spend a few hours, if you tell me what fits the overall strategy.

**Comment by physikerwelt** [comment]
As discussed with @brightbyte via mail, https://github.com/wikimedia/restbase/pull/1324 is the alternative approach to redirect from png to SVG images.

**Pull request closed without merging**
