### PR TITLE
Added 'displaytitle' property to the summary

### PR DESCRIPTION
**Pull request by Pchelolo**
Goes together with #809 

Bug: https://phabricator.wikimedia.org/T163729
cc @wikimedia/services

### CODE REVIEW

**Comment by coreyfloyd** [comment]
👍

**Comment by d00rman** [comment]
Needs a rebase now :)

**Comment by d00rman** [comment]
Also, let's bump the content version as we discussed.

**Comment by Pchelolo** [comment]
@d00rman rebased!

**Pull request merged**
