### PR TITLE
Add sequence diagram for current VE page edit workflow

### PR DESCRIPTION
**Pull request by earldouglas**
This was reverse-engineered from the VE sandbox and the VE extension source.  Needs a quick double-check for accuracy.

See the diagram here: https://github.com/earldouglas/restbase/blob/be707e4e8136ce7e6c8176792d5bd993e137d356/doc/visualeditor/page-edit.svg

### CODE REVIEW

**Comment by gwicke** [comment]
Should this live in the VE extension?

**Comment by catrope** [comment]
How about on mediawiki.org?

(Also if you want to deploy RESTbase soon, why is the repo still on github?)

**Comment by earldouglas** [comment]
These diagrams can live wherever's most appropriate, but for this PR let's focus on reviewing them for accuracy.

**Comment by earldouglas** [comment]
That reminds me, I should include the source for these diagrams.  Stand by for ninja-commit...

**Comment by gwicke** [comment]
@catrope, we have a github mirror for deploys. We like to run tests before merging, which is why we are currently using github + travis.

**Comment by catrope** [comment]
The Parsoid HTTP API isn't represented accurately here. The URL format is `/enwiki/Barack_Obama?oldid=12345` . Accounting for the oldid not being there is pointless because `/enwiki/Barack_Obama` just 301s to `/enwiki/Barack_Obama?oldid={latest oldid}`

**Comment by earldouglas** [comment]
@catrope How does `postHTML` get translated into that URL?

*ApiVisualEditor.php:*

```php
	protected function postHTML( $title, $html, $parserParams ) {
		if ( $parserParams['oldid'] === 0 ) {
			$parserParams['oldid'] = '';
		}
		return $this->requestParsoid(
			'POST',
			'transform/html/to/wikitext/' . urlencode( $title->getPrefixedDBkey() ),
			array(
				'html' => $html,
				'oldid' => $parserParams['oldid'],
			)
		);
	}
```

Related: how do I link to a line of code using Gerrit (so I don't have to copy/paste here)?

**Comment by catrope** [comment]
It gets transformed by ParsoidVirtualRESTService in MW core. This was changed recently, that's why I didn't recognize the /transform/html/to/wiktext thing.

https://git.wikimedia.org/blob/mediawiki%2Fcore.git/e271a4f3eb533c05b9ea1a7a46e4608c55017bae/includes%2Flibs%2Fvirtualrest%2FParsoidVirtualRESTService.php#L27

**Comment by gwicke** [comment]
So.. should this live on mediawiki.org?

**Comment by earldouglas** [comment]
I'll move it to mediawiki.org.

**Comment by earldouglas** [comment]
Added here: https://www.mediawiki.org/wiki/VisualEditor#Documentation

**Pull request closed without merging**
