### PR TITLE
Update dependencies and release v0.18.0

### PR DESCRIPTION
**Pull request by d00rman**
Bug: [T184199](https://phabricator.wikimedia.org/T184199)

### CODE REVIEW

**Comment by d00rman** [comment]
cc @wikimedia/services .

A question here is: could this potentially be v1.0.0 instead of v0.18.0 ?

**Comment by Pchelolo** [comment]
> A question here is: could this potentially be v1.0.0 instead of v0.18.0 ?

I think we should make 1.0 somewhat more remarkable than just a version bump. With an announcement etc

**Comment by d00rman** [comment]
> I think we should make 1.0 somewhat more remarkable than just a version bump. With an announcement etc

I feel the same, that's why I put v0.18.0 here.

**Comment by d00rman** [comment]
Published as [v0.18.0](https://github.com/wikimedia/restbase/tree/v0.18.0)

**Pull request merged**
