### PR TITLE
More efficient revision query

### PR DESCRIPTION
**Pull request by gwicke**

### CODE REVIEW

**Comment by gwicke** [comment]
Still timing out the background update query, see https://phabricator.wikimedia.org/T107640

**Comment by d00rman** [comment]
LGTM except the `--no-timeouts` issue I mentioned in #292

**Comment by Pchelolo** [comment]
LGTM too, only thing is `--no-timeouts` wouldn't work any more, because the testing infrastructure was changed when SQLite testing mode was created.

**Comment by gwicke** [comment]
Okay, dropped the timeout patch from this PR.

**Pull request merged**
