### PR TITLE
Add Suggested Edits endpoints to Recommendations

### PR DESCRIPTION
**Pull request by mdholloway**
Adds four new recommendation endpoints:

- /data/recommendation/caption/addition/{target}
- /data/recommendation/caption/translation/from/{source}/to/{target}
- /data/recommendation/description/addition/{target}
- /data/recommendation/description/translation/from/{source}/to/{target}

The caption suggestion endpoints are supported for Commons domains,
and the description suggestion endpoints are supported for Wikidata domains.

Phab: https://phabricator.wikimedia.org/T224754

### CODE REVIEW

**Comment by Pchelolo** [comment]
Ok, so you gave up on the x-ample tests :) 

Lemme merge this and try to experiment with that a little..

**Comment by Pchelolo** [comment]
After travis is passing

**Comment by mdholloway** [comment]
Yeah, they pass with Beta Cluster domains but not with prod domains (which makes sense given that that's what the test configs point to).  So we can re-add those for BC domains and set monitoring to true if you want.

**Comment by Pchelolo** [comment]
> Yeah, they pass with Beta Cluster domains but not with prod domains (which makes sense given that that's what the test configs point to). So we can re-add those for BC domains and set monitoring to true if you want.

I actually think it might be a bit harder, since operations-software-service-checker script is involved too. I think I'll just merge this once Travis is done and followup

**Comment by Pchelolo** [comment]
Actually, I need to file a followup ticket here with these x-amples tests. The thing is that in production only endpoints from `en.wikipedia.org` endpoints are checked and all the rest are ignored. Given that we have a non-zero number of endpoints that are not on enwiki, we need some enhancements on how we execute the checks in prod. 

For now, could you please write a couple of tests in just plain javascript for these endpoints and add a comment that "TODO convert it to x-amples once we support running x-amples for multiple domains.

**Comment by mdholloway** [comment]
OK, added tests. Not sure what's up with Travis but it seemed stalled earlier.

**Pull request merged**
