### PR TITLE
Description update to use aqs_default in prod

### PR DESCRIPTION
**Pull request by milimetric**
Also added content-type headers to all responses because hyperswitch
doesn't add any by default (it shouldn't).  See the mailing list:

https://lists.wikimedia.org/pipermail/analytics/2016-February/004908.html

Bug: T122249

### CODE REVIEW

**Comment by gwicke** [comment]
Strictly speaking UTF-8 is [implied by application/json](https://www.ietf.org/rfc/rfc4627.txt):

> JSON text SHALL be encoded in Unicode.  The default encoding is UTF-8.

So, one could argue that Chrome should default to that when displaying JSON. However, it's only adding a couple bytes, and if it helps read the JSON more comfortably in Chrome.. why not.

**Comment by gwicke** [comment]
:+1: overall, but waiting for travis.

**Comment by d00rman** [comment]
> overall, but waiting for travis.

yeah, me too... :)

**Comment by milimetric** [comment]
i was a bit surprised by this bug too.  Encoding problems ftl :/

**Comment by d00rman** [comment]
Travis seems to be out. I checked it locally and all's good (as expected), so merging.

**Pull request merged**
