### PR TITLE
Expose /page/metadata and /page/references endpoints via RESTBase

### PR DESCRIPTION
**Pull request by berndsi**
This is pretty much the same as was done for /page/media. Going to do references later.

Bug: T190198
Bug: T189750

### CODE REVIEW

**Comment by Pchelolo** [comment]
LGTM. We need a rule to purge it in change-prop, I'll make necessary changes. 

When do you want this deployed?

**Comment by berndsi** [comment]
I think this can wait until I got the pr for references as well. Tomorrow
would be fine.

**Comment by Pchelolo** [comment]
The test failures are unrelated. Needs to be rebased on #974 after that one is merged.

**Comment by berndsi** [comment]
Since I'll have to also change some of the same files for the new references endpoint, should I just add to this PR?

**Comment by Pchelolo** [comment]
yup @berndsi go for it

**Pull request merged**
