### PR TITLE
Support new MCS response format

### PR DESCRIPTION
**Pull request by Pchelolo**
See https://gerrit.wikimedia.org/r/#/c/338288/1 for more context

cc @wikimedia/services @berndsi

### CODE REVIEW

**Comment by berndsi** [comment]
-1 With this and the new MCS patch you only get `selected` filled out in  http://localhost:7231/en.wikipedia.org/v1/feed/onthisday/all/01/01 . The other four are empty arrays.

**Comment by Pchelolo** [comment]
The 'onthisday' in RESTBase doesn't use the individual endpoints, but /all endpoint which shouldn't have been changed?

**Comment by d00rman** [comment]
@berndsi perhaps you are testing this with the upcoming version of MCS instead of the currently-deployed one?

**Comment by berndsi** [comment]
@Pchelolo Then I don't understand why we need a code change in RESTBase.
@d00rman Yes, I test this with both master and the new MCS patch applied. The goal of this RB patch is that it works with both.

**Comment by Pchelolo** [comment]
> @Pchelolo Then I don't understand why we need a code change in RESTBase.

The feed/featured has selected anniversaries in it and it's using the individual endpoint to fetch it.

**Comment by berndsi** [comment]
Right, I forgot about that since I haven't seen the selected anniversaries appear in practice. Example: https://en.wikipedia.org/api/rest_v1/feed/featured/2017/02/22 . I do remember seeing code that should do this in theory.

**Comment by Pchelolo** [comment]
@berndsi Ok, updated the PR. Apparently it was broken because I forgot to add a `/feed/` portion in one of the URI templates.

**Comment by berndsi** [comment]
Weird. Not sure what happened. I can't reproduce the issue I reported earlier. Maybe a DB issue since I blew away my old sqlite.db file, and now it works.

**Comment by Pchelolo** [comment]
@berndsi To avoid it going to the storage for the content, try doing requests with `-H 'Cache-Control: no-cache`

**Pull request merged**
