### PR TITLE
Spec cleanup

### PR DESCRIPTION
**Pull request by gwicke**
Implement ideas from https://phabricator.wikimedia.org/T118700.

- [x] Un-prefixed dotted path references and function calls.
- [x] `{{foo}}` syntax in all attributes.
- [x] wrap responses in `responses` object
- [x] shorten / alias `request` to `req`

### CODE REVIEW

**Comment by gwicke** [comment]
See also #419 for module option templating support.

**Comment by d00rman** [comment]
> shorten / alias request to req

We agreed we'd continue using `request` so this alias should be removed, IMO.

**Comment by gwicke** [comment]
> We agreed we'd continue using request so this alias should be removed, IMO.

It is removed in #421.

**Comment by d00rman** [comment]
Incorporated in #421, closing.

**Pull request closed without merging**
