### PR TITLE
Bump mobile-html and mobile-html-offline-resources filter version to 1.2.1

### PR DESCRIPTION
**Pull request by joewalsh**
https://phabricator.wikimedia.org/T249150

### CODE REVIEW

**Comment by Pchelolo** [comment]
LGTM. When do you need this to be deployed?

**Comment by joewalsh** [comment]
@Pchelolo later this week or early next week would be ideal. Same for #1251

**Comment by Pchelolo** [comment]
Was mcs/pcs deployed already so I can proceed and deploy this any time?

**Comment by joewalsh** [comment]
Yes, mcs/pcs was deployed with the new version

**Comment by Pchelolo** [comment]
When do you need this deployed? I can do tomorrow probably

**Comment by joewalsh** [comment]
@Pchelolo could you merge #1251 before deploying? That's the bigger blocker for us. Today would be great, early next week (before Thursday) is fine too.

**Pull request merged**
