### PR TITLE
Pull in cassandra driver v2 for testing

### PR DESCRIPTION
**Pull request by gwicke**
Don't merge until we have tested this a bit on the test cluster.

### CODE REVIEW

**Comment by d00rman** [comment]
Hm, I see a new `cassandra_driver_v2` branch in this repo, but this PR does not use it al all. A typo? IMHO, it should be better/easier to test if these commits were made in wikimedia/restbase/cassandra_driver_v2 than gwicke/restbase/cassandra_driver_v2.

**Comment by gwicke** [comment]
@d00rman, I had the same thought, but then realized that it actually matters more how we push this into the deploy repo. I already used this code for wiki creation testing yesterday, where the v2 driver proved reliable.

**Comment by gwicke** [comment]
Merging without waiting for travis after triple-checking the tests locally. Travis seems to be down right now.

**Comment by gwicke** [comment]
The travis run was actually fine, only the reporting failed apparently: https://travis-ci.org/wikimedia/restbase/builds/53063025

**Pull request merged**
