### PR TITLE
Update restbase-mod-table-cassandra to v0.9.0

### PR DESCRIPTION
**Pull request by gwicke**

### CODE REVIEW

**Comment by d00rman** [comment]
`git log` tells me we have the following outstanding PRs to deploy:
- #575 
- #571 

I'd vote for getting that deployed before merging this. Thoughts?

**Comment by gwicke** [comment]
@d00rman: Both of those aren't terribly important / user-visible. One is literally a maintenance script, the other a minor performance optimization.

**Comment by Pchelolo** [comment]
Merging to start testing in labs/staging

**Pull request merged**
