### PR TITLE
Make each test runnable in isolation

### PR DESCRIPTION
**Pull request by earldouglas**
This makes the tests a bit more developer-friendly.  Each test can:

* start the restbase server (no-op if it's already started)
* restart the server (if the desired server configuration is different than what's currently running)
* be run in isolation:
  * single file: `mocha test/parsoid/ondemand.js`
  * single directory: `mocha test/parsoid`

Now we can rapidly develop against a single test (or set of tests) via:

```
fswatch mocha test/parsoid
```

### CODE REVIEW

**Comment by earldouglas** [comment]
TODO:

* [ ] Update the README.md with all the various means of testing

**Comment by earldouglas** [comment]
Oh bother, it looks like our coverage testing is not `--recursive` like mocha.  Investigating...

**Comment by earldouglas** [comment]
Note: cleaned up the description a bit -- all that bash magic was unnecessary.

**Comment by hardikj** [comment]
This pull require a rebase

**Comment by hardikj** [comment]
Looks good to me overall

**Comment by earldouglas** [comment]
Closing in favor of #145.

**Pull request closed without merging**
