### PR TITLE
Update dependencies' versions and release v0.7.12

### PR DESCRIPTION
**Pull request by d00rman**

### CODE REVIEW

**Comment by d00rman** [comment]
For me locally, the *detect conflict on save HTML* test is failing, both for master and this branch:

```
Expected:
409
Result:
400
```

That isn't happening for Travis, though. Hm.

**Comment by d00rman** [comment]
cc @gwicke @Pchelolo @eevans

**Comment by Pchelolo** [comment]
@d00rman Just checked, for me all save_api tests fail because labs wiki returns ` DB connection error: Can't connect to MySQL server on '10.68.17.94'`.

**Comment by d00rman** [comment]
That seemed to had been caused by an outdated `request` dependency of `preq`. After updating, the test is passing.

But, now I can't get past the jshint test though. The process uses 100% and never finishes ...

**Comment by eevans** [comment]
> But, now I can't get past the jshint test though. The process uses 100% and never finishes ...

FWIW, everything passes for me locally.

**Comment by d00rman** [comment]
All good for me too, now. Wrt jshint, the culprits were some huge temp files I had laying around in the repo's dir.

**Comment by eevans** [comment]
We are ready to perform the staging rebuild as part of https://phabricator.wikimedia.org/T108613, but before doing so need to update the staging clusters replication.  I'd like to test that part of the process with https://phabricator.wikimedia.org/T76494 (tied to this PR as it is in rb-m-t-cassandra 0.8.0), so I'm +1 on seeing this merged and deployed to staging.

**Pull request merged**
