### PR TITLE
Added public anniversaries endpoints

### PR DESCRIPTION
**Pull request by Pchelolo**
Adding buckets and public API for the `onthisday` feature.

Bug: https://phabricator.wikimedia.org/T143420

### CODE REVIEW

**Comment by d00rman** [comment]
According to the ticket, the final layout might slightly change, so let's hold off on this one until the discussion settles.

**Comment by Pchelolo** [comment]
@d00rman That's why I wrote 'pending naming discussion' in the description :)

**Comment by d00rman** [comment]
> @d00rman That's why I wrote 'pending naming discussion' in the description :)

Touche :)

**Comment by Pchelolo** [comment]
Updated to name the endpoint `onthisday` per discussion on the task. Deploy pending MCS deployment.

**Comment by d00rman** [comment]
@Pchelolo there are still references to //anniversaries// in both the code and Swagger definitions. Perhaps it would be better to rename those to //onthisday// for consistency?

**Comment by Pchelolo** [comment]
@d00rman Updated. Removed all references to `anniversaries`

**Pull request merged**
