### PR TITLE
Added rvslots=main to the MW API revision request.

### PR DESCRIPTION
**Pull request by Pchelolo**
Bug: https://phabricator.wikimedia.org/T201974

### CODE REVIEW

**Comment by mdholloway** [comment]
Looks like there's a call that needs fixing in a test, too: https://github.com/wikimedia/restbase/blob/master/test/features/errors/invalid_request.js#L32-L42

**Comment by Pchelolo** [comment]
Oh thank you, great find @mdholloway

**Comment by mdholloway** [comment]
Actually, now that I look closer, why are you requesting contentmodel?  It doesn't appear to be used.

**Comment by Pchelolo** [comment]
Hm... ok. let's redo this :)

**Pull request merged**
