### PR TITLE
Rename pageview to metrics and add unique devices

### PR DESCRIPTION
**Pull request by jobar**
Rename pageview definition to metrics in order to have only one file defining metrics redirections to AQS.
Add unique devices entry point to this file.

### CODE REVIEW

**Comment by d00rman** [comment]
This is blocked until https://gerrit.wikimedia.org/r/#/c/277784/ is deployed. @jobar / @milimetric please ping us here once that happens.

**Comment by jobar** [comment]
Ping guys ! We have found the loading issue, doesn't come from restbase nor cassandra per say (cassandra java driver). Would you mind considering merging/deploy this PR ?

**Comment by Pchelolo** [comment]
@jobar Did you already deploy on your end? We can deploy it later today I think

**Comment by jobar** [comment]
@Pchelolo Yes, everything deployed on our end.
Let us know when you deploy the change, for us to test.
Thanks !

**Pull request merged**
