### PR TITLE
Parsoid: Empty the list of pages that we don't want to re-render

### PR DESCRIPTION
**Pull request by MatmaRex**
Perf improvements and resource limit improvements made it unnecessary,
and it hasn't been updated in years.

The list is a problem because we want to parse some of these pages now.
See https://phabricator.wikimedia.org/T316914

### CODE REVIEW

**Review by thesocialdev — APPROVED** [review]
LGTM. I will give an opportunity to others to chime in before merging it.

**Comment by kemayo** [comment]
Seems like nobody wants to chime in -- want to go ahead and merge?

**Review by thesocialdev — APPROVED** [review]

**Comment by thesocialdev** [comment]
I don't have merge rights, @johngian will look at it.

**Comment by johngian** [comment]
Looks good to me.

**Comment by johngian** [comment]
Looks good to me. On top of that this config is picked up by the tests so restbase initialization should work fine.

**Comment by MatmaRex** [comment]
Thanks for the reviews. It looks like the change is not deployed to Wikimedia wikis yet. Is that automated like the deployment train, or what would it take to make that happen?

**Comment by MatmaRex** [comment]
(It was deployed by @johngian)

Thank you both for the reviews!

**Pull request merged**
