### PR TITLE
Update swagger-router dependency

### PR DESCRIPTION
**Pull request by gwicke**

### CODE REVIEW

**Comment by d00rman** [comment]
swagger-router's version is still [held at 0.0.3](https://github.com/wikimedia/swagger-router/blob/master/package.json#L3). Am I missing something, @gwicke ?

**Comment by gwicke** [comment]
Good catch: Forgot to create a PR. Now done: https://github.com/wikimedia/swagger-router/pull/17

**Comment by gwicke** [comment]
@d00rman, also published 0.0.4 already to npmjs.org.

**Comment by d00rman** [comment]
Heh, not losing any time I see :smile:

**Pull request merged**
