### PR TITLE
Use eslint

### PR DESCRIPTION
**Pull request by Pchelolo**
ESLint is the new generation of static code analysis tools coming to replace JSCS and JSHint. 

I imagine the eslint config would become an endless source of bike shedding, because what I wanna achieve is to settle on the common eslint config for all node services we maintain :)

The current config was generated by analysing our current RESTBase code-style

cc @wikimedia/services

### CODE REVIEW

**Comment by d00rman** [comment]
The es config seems to be missing here.

**Comment by Pchelolo** [comment]
Ups, forgot to `git add` it..

**Comment by Pchelolo** [comment]
And here we are, on the crossroads. eslint itself is node 4+

**Comment by d00rman** [comment]
Yup, @Pchelolo . But I don't think that's bad per se, we want to drop node 0.x anyway. Let's wait a bit with this PR, though.

**Comment by Pchelolo** [comment]
Same functionality implemented in #681. Closing

**Pull request closed without merging**
