### PR TITLE
Minor feed bug for no-cache request for non-existent historic content

### PR DESCRIPTION
**Pull request by Pchelolo**
cc @wikimedia/services @berndsi

### CODE REVIEW

**Comment by gwicke** [comment]
What is the reason for returning 204 instead of 404 here? Are there specific expectations in the app about this?

**Comment by Pchelolo** [comment]
@gwicke Basically we want to completely ignore the `404` error and return a normal result so that we end up in the `.then`. We cannot `return 404` because hyper switch disallows plain returning erroneous codes and automagically wraps them into an HTTPError and throws.

**Comment by gwicke** [comment]
@Pchelolo, could we instead .catch the 404 where we need to handle it?

**Comment by Pchelolo** [comment]
@gwicke This is where we need to handle it that's why we 'catch' it here. 
The logic is: for the historic content with a `no-cache` request, we need to check the stored content, because not everything can be regenerated historically and regenerate all pieces of the feed that can be regenerated and re-save those which can't. If there's no historic content (404) - that's fine, just return an 'empty' response. You cannot 'catch' one part of the `P.join` request and not the other part anyhow differently from what we're doing here.

**Comment by d00rman** [comment]
Right, this makes sense to me since we need to return all of the components that we can when regenerating the historic feed :+1:

**Comment by gwicke** [comment]
My concern is more about using 204 when semantically a 404 seems like what we really would want here. If the concern is just the .join, can't we just return a 404 code that is not an error from the .catch? That wouldn't trigger any HTTPError wrapping, and would thus not interfere with promise chaining.

**Comment by Pchelolo** [comment]
@gwicke Done.

**Comment by gwicke** [comment]
:+1:

**Pull request merged**
