### PR TITLE
Pushing computing delta into timing module

### PR DESCRIPTION
**Pull request by arlolra**
Is that desirable?

### CODE REVIEW

**Comment by earldouglas** [comment]
Makes sense to me.

**Comment by gwicke** [comment]
I left it out as passing in the timing seemed slightly more flexible (can add up several timings to one aggregate etc). Don't care too strongly though.

**Comment by arlolra** [comment]
The common case is tedious though,
https://gerrit.wikimedia.org/r/#/c/186219/7/api/routes.js

You can always pass in (Date.now() - aggregate) :)

**Comment by gwicke** [comment]
Maybe the start time could be an optional parameter for the best of both worlds?

**Comment by arlolra** [comment]
> Maybe the start time could be an optional parameter for the best of both worlds?

The signature would start to get ugly. I don't like passing in a `null` for `delta` in that case.

I guess just adding a wrapper would suffice.

    StatsD.prototype.endTimer = function( name, suffix, start ) {
      return this.timing( name, suffix, Date.now() - start );
    }

Or maybe this has been enough of a distraction already :)

**Comment by gwicke** [comment]
@arlolra, my idea was an optional last parameter, like this:

```javascript
// Implicit delta calculation
statsd.timing( name, suffix, Date.now(), startTime );

// Plain timing as it works right now
statsd.timing( name, suffix, timeDelta );

**Comment by gwicke** [comment]
@arlolra, that would work for me. Perhaps call it `endTiming` instead for some consistency?

**Comment by arlolra** [comment]
You've s/-/,/ :)

`endTiming` sounds good. Or, `captureTiming`? (suggested just to keep this conversation going)

**Comment by gwicke** [comment]
> (suggested just to keep this conversation going)

Ha! We'll move this code to a separate package so that we can share it. Can add the method then.

**Comment by arlolra** [comment]
Oh ... too late. And I merged in #175.

**Comment by gwicke** [comment]
@arlolra: alright, thank you!

**Pull request merged**
