### PR TITLE
Transforms: Add /wikitext/to/lint{/title}

### PR DESCRIPTION
**Pull request by d00rman**
Depends-On: https://gerrit.wikimedia.org/r/#/c/352715/
Bug: [T163091](https://phabricator.wikimedia.org/T163091)

### CODE REVIEW

**Comment by d00rman** [comment]
cc @wikimedia/services @wikimedia/parsing

**Comment by arlolra** [comment]
LGTM.  A title/revid can be supplied if you want to support T164006

**Comment by d00rman** [comment]
@arlolra added the revision parameter since Parsoid supports it (mostly for compatibility with other transform end points).

**Comment by arlolra** [comment]
Sounds good

**Comment by d00rman** [comment]
@subbuss @arlolra ping me here once the Parsoid side has been deployed and we'll get this one going too.

**Comment by d00rman** [comment]
The corresponding Parsoid change has been merged, so we are good to go on this one.

**Pull request merged**
