### PR TITLE
Save SQLite DB file to temp location 

### PR DESCRIPTION
**Pull request by Pchelolo**
For testing, we run in SQLite mode in docker and so can't create the test file in current directory because of permissions. Instead, let's create the DB file in OS temp location.

cc @wikimedia/services @akosiaris

### CODE REVIEW

**Comment by eevans** [comment]
Insofar as I understand what `insecurely: true` is doing (`COPY [., .]`), this seems reasonable (though I'm not sure I actually understand/appreciate the insecurity).

One alternative would be to create the sqlite database as a unique temp file (the JS equivalent of something like `mktemp -t sqlite.XXXXXXXXXX`), log the resulting filename in case locating it for debugging is required, and leave it to the OS to clean them up.  This might result in more robust tests anyway (for example, ensuring each test run gets a fresh database, keeping the working directory free of detritus, etc)

But to be clear, I'm personally OK with the PR as submitted.  :+1:

**Comment by akosiaris** [comment]
> Insofar as I understand what insecurely: true is doing (COPY [., .]), this seems reasonable (though I'm not sure I actually understand/appreciate the insecurity).

insecurely means that it skips the step separating the owner of the files from the execution user. That is, instead of switching running the commands under the `runuser` the commands will be run using the `somebody` user. Useful while still changing the image. But it could have been named better I think.

LGTM.

**Comment by Pchelolo** [comment]
Thanks @eevans and @akosiaris 

I have changed the premise of the PR to create DB file in the temp directory.

**Comment by eevans** [comment]
Nice; I like it! :+1:

**Pull request merged**
