### PR TITLE
Release v0.19.0

### PR DESCRIPTION
**Pull request by d00rman**

### CODE REVIEW

**Comment by Pchelolo** [comment]
travis travis...

**Comment by d00rman** [comment]
My branch failed - https://travis-ci.org/d00rman/restbase/builds/402118758 - for the SF summary, but I guess that's expected. However, will that now start failing the checks in prod too? If so, we cannot dpeloy until MCS fixes its part...

**Comment by Pchelolo** [comment]
MCS is actually failing because of RESTBase https://github.com/wikimedia/restbase/pull/1014, so deploying should fix it, not break further.

**Comment by Pchelolo** [comment]
none of the unexpected tests failed, so LGTM. I propose to deploy this.

**Comment by d00rman** [comment]
Released as [v0.19.0](https://github.com/wikimedia/restbase/tree/v0.19.0)

**Pull request merged**
