### PR TITLE
Don't try upgrading if .minor version is satisfied ok

### PR DESCRIPTION
**Pull request by Pchelolo**
https://github.com/wikimedia/restbase/pull/1052#pullrequestreview-158677694

cc @wikimedia/services @arlolra

### CODE REVIEW

**Comment by arlolra** [comment]
LGTM

**Comment by arlolra** [comment]
Maybe deserves a test?

**Comment by Pchelolo** [comment]
actually, just found another weirness. hold on

**Comment by Pchelolo** [comment]
Updated. It does deserve a test indeed, but I'm having troubles creating one. These two issues are for content version upgrade, not downgrade, so we need somehow to obtain the previous version first to store it. Since the tests are running against deployed parsoid, we can only get the upgraded version, not the previous one. I guess I need to mock parsoid first to provide a fake lover version...

**Comment by d00rman** [comment]
Needs a rebase.

**Comment by d00rman** [comment]
Rebased, waiting on travis to merge

**Pull request merged**
