### PR TITLE
DO NOT MERGE: CI Test

### PR DESCRIPTION
**Pull request by physikerwelt**
Change-Id: I5588383c8a700c619a9bf40173b61c5495ee8202

### CODE REVIEW

**Comment by physikerwelt** [comment]
@johngian do you know why tests fail?

**Comment by physikerwelt** [comment]
It seems tests try accessing http://parsoid-external-ci-access.beta.wmflabs.org/. However, I realized that .wmflabs.org domains can no longer be managed via horizon. Thus one might have to switch to a wmcloud domain. https://wikitech.wikimedia.org/wiki/Wikimedia_Cloud_Services_team/EnhancementProposals/DNS_domain_usage

**Comment by johngian** [comment]
I send a PR that fixes 2 out of 4 failing tests. This is caused by language variant code format that was released. The other 2 I am still trying to figure out the cause.

**Comment by johngian** [comment]
CI should be fixed after: #1315

**Pull request closed without merging**
