### PR TITLE
Update summary spec

### PR DESCRIPTION
**Pull request by berndsi**
* Update endpoint summary and description
* Bump version

This PR is in preparation for #1263.

Bug: https://phabricator.wikimedia.org/T251959

### CODE REVIEW

**Comment by berndsi** [comment]
CI failures due to https://phabricator.wikimedia.org/T255157.

**Comment by mdholloway** [comment]
Is there a Phab task associated with this change?  If not, we should create one and tag it with #core_platform_team so that they can see it and triage it.

**Comment by Pchelolo** [comment]
> Is there a Phab task associated with this change? If not, we should create one and tag it with #core_platform_team so that they can see it and triage it.

It will circle back to me. I apologize for all the delay here, it's somehow escaped my view. I'm gonna get all these to a merge by the end of the week.

**Comment by berndsi** [comment]
> Is there a Phab task associated with this change? If not, we should create one and tag it with #core_platform_team so that they can see it and triage it.

Updated the PR description with links.

**Comment by Pchelolo** [comment]
Covered by #1263

**Pull request closed without merging**
